name: rikulo_highcharts
version: 2.0.4
description: Highcharts is a wrapper of highcharts in Dart.
homepage: https://github.com/rikulo/highcharts
documentation: https://pub.dev/documentation/rikulo_highcharts/latest/
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  js: any
